## =============================================================================
## module_9sp/R_figures/figure_env_structure_alignment.R
##
## Supplementary diagnostic figure comparing observed environment--structure
## alignment in the two empirical panels with the alignment preserved or
## generated by their structure-aware null phenotypes.
## =============================================================================
suppressMessages({library(data.table); library(ggplot2); library(patchwork)})

ROOT <- path.expand("~/gitlab/LDscnR-paper")
IN <- file.path(ROOT, "module_9sp", "out", "02b_env_structure_alignment",
                "alignment.rds")
FIG_DIR <- file.path(ROOT, "module_9sp", "figures")
dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)

x <- readRDS(IN)
obs <- copy(x$observed)
nd <- copy(x$null_draws)

## Panel a: alignment with the categorical sampling structure used to construct
## each label-permutation null. Show both population-level weighting (matching
## the simulation comparison) and individual weighting (matching the scan).
a <- melt(
  obs[phenotype == "Raw habitat"],
  id.vars = c("species", "structure_group"),
  measure.vars = c("structure_r2_population",
                   "structure_r2_individual_weighted"),
  variable.name = "weighting", value.name = "r2"
)
a[, weighting := factor(
  weighting,
  levels = c("structure_r2_population", "structure_r2_individual_weighted"),
  labels = c("Populations weighted equally", "Individuals weighted equally")
)]
a[, species_short := factor(
  species,
  levels = c("Three-spined stickleback", "Nine-spined stickleback"),
  labels = c("Three-spined\n(region)", "Nine-spined\n(lineage)")
)]

p1 <- ggplot(a, aes(species_short, r2, colour = weighting, group = weighting)) +
  geom_point(position = position_dodge(width = 0.35), size = 3) +
  scale_colour_manual(values = c("#2166AC", "#B2182B")) +
  scale_y_continuous(limits = c(0, 0.8), expand = expansion(mult = c(0, 0.04))) +
  labs(x = NULL, y = expression(R^2), colour = NULL,
       title = "Alignment with null-defining groups") +
  theme_bw(10.5) +
  theme(panel.grid.minor = element_blank(), legend.position = "bottom",
        plot.title = element_text(size = 10.5, face = "bold"))

## Panel b: the simulation-comparable five-GRM-axis measure. Each violin is a
## null distribution; diamonds are observed values. Raw and adjusted 9sp
## phenotypes are kept separate because only the latter enters the scan.
nd[, case := fcase(
  species == "Three-spined stickleback",
    "3sp\nraw habitat\nregional null",
  species == "Nine-spined stickleback" & phenotype == "Raw habitat",
    "9sp\nraw habitat\nlineage null",
  species == "Nine-spined stickleback" &
    phenotype == "Lineage-adjusted habitat" &
    scheme == "Within-lineage label permutation",
    "9sp\nadjusted habitat\nlineage null",
  default = "9sp\nadjusted habitat\nGRM null"
)]
case_levels <- c(
  "3sp\nraw habitat\nregional null",
  "9sp\nraw habitat\nlineage null",
  "9sp\nadjusted habitat\nlineage null",
  "9sp\nadjusted habitat\nGRM null"
)
nd[, case := factor(case, levels = case_levels)]
obs_points <- unique(nd[, .(species, phenotype, case)])
obs_points <- merge(
  obs_points,
  obs[, .(species, phenotype,
          observed = grm_axes_r2_population)],
  by = c("species", "phenotype"), all.x = TRUE
)

p2 <- ggplot(nd, aes(case, grm_axes_r2_population, fill = scheme)) +
  geom_violin(width = 0.85, scale = "width", colour = "grey45", linewidth = 0.25) +
  geom_point(data = obs_points,
             aes(case, observed), inherit.aes = FALSE,
             shape = 23, fill = "black", colour = "white", size = 3.1,
             stroke = 0.5) +
  scale_fill_manual(values = c(
    "Within-region label permutation" = "#92C5DE",
    "Within-lineage label permutation" = "#F4A582",
    "GRM-matched continuous null" = "#B2ABD2"
  )) +
  scale_y_continuous(limits = c(0, 1), expand = expansion(mult = c(0, 0.02))) +
  labs(x = NULL, y = expression(R^2), fill = NULL,
       title = "Alignment with five relationship-matrix axes") +
  theme_bw(10.5) +
  theme(panel.grid.minor = element_blank(), legend.position = "bottom",
        plot.title = element_text(size = 10.5, face = "bold"),
        axis.text.x = element_text(size = 8.6))

fig <- (p1 | p2) + plot_layout(widths = c(0.8, 1.6)) +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(face = "bold", size = 12))

pdf_out <- file.path(FIG_DIR, "figureS_empirical_env_structure_alignment.pdf")
png_out <- file.path(FIG_DIR, "figureS_empirical_env_structure_alignment.png")
ggsave(pdf_out, fig, width = 10.5, height = 4.8, device = cairo_pdf)
ggsave(png_out, fig, width = 10.5, height = 4.8, dpi = 250)
cat("Wrote", pdf_out, "and", png_out, "\n")
