## =====================================================================
## module_sim_LDscnR / make_table2.R
##
## Generates tables/table2_method_definition.tex for the LDscnR manuscript:
## the Phase 0 record of what the canonical method IS, one row per frozen
## decision, with the evidence from BOTH datasets beside it.
##
## GENERATED, NOT TYPED. Three numbers reached a co-authored manuscript today by
## being typed from memory and each was caught only by someone asking where it
## came from. The sims column here is computed from results/ on every run.
##
## THE PANEL COLUMN IS NOT MINE TO COMPUTE. Those figures come from ldscnr-2c's
## R_3sp_blocks/01_units_and_scan.R and are carried here as constants with their
## source named. They are cross-checkable by re-running that script; they are not
## re-derived here, and this file should not pretend otherwise.
##
## Rows are added as Phase 0 items are decided. An undecided item has no row.
##   Rscript module_sim_LDscnR/make_table2.R
## =====================================================================
suppressMessages(library(data.table))
OUT <- path.expand("~/gitlab/LDscnR_manuscript/tables/table2_method_definition.tex")
RES <- "module_sim_LDscnR/results"

## ---- item 1: inferential unit -----------------------------------------
d <- fread(file.path(RES, "engine_x_statistic.csv"))
w <- dcast(d, cell + env + statistic + engine ~ partition,
           value.var = c("n_test", "recall", "precision"))
setnames(w, gsub(" ", "", names(w))); w <- w[complete.cases(w)]
sims_mult <- mean(w$n_test_stage2) / mean(w$n_test_stage1)     # stage2 relative to stage1
sims_drec <- mean(w$recall_stage2 - w$recall_stage1)
sims_nlow  <- sum(w$recall_stage2 <  w$recall_stage1)   # strictly worse
sims_ntie  <- sum(w$recall_stage2 == w$recall_stage1)   # tied
sims_nhigh <- sum(w$recall_stage2 >  w$recall_stage1)   # better -- expected 0

## ldscnr-2c, R_3sp_blocks/01_units_and_scan.R, floor 8, regions lumped at 300 kb
pan <- list(s1_units = 1305L, s2_units = 2631L, s1_cons_disc = 79L, s2_cons_disc = 5L)
pan_mult <- pan$s2_units / pan$s1_units

## ---- item 2 (part): stage-2 distance threshold ------------------------
## Read from the bundle builder rather than retyped, so the table cannot drift
## from what the analyses actually ran with.
src  <- readLines("module_sim_LDscnR/regen_sim_data.R")
dt   <- sub(".*distance_threshold *= *([0-9.e+]+).*", "\\1",
            grep("distance_threshold *=", src, value = TRUE)[1])
scor <- vapply(c("engine_x_statistic.R","test_then_cluster.R","span_matched_precision.R",
                 "stage1_vs_stage2_units.R"),
       function(f) { l <- grep("distance_threshold *=", readLines(file.path("module_sim_LDscnR", f)), value = TRUE)
                     sub(".*distance_threshold *= *([0-9.e+]+).*", "\\1", l[1]) }, character(1))
stopifnot(length(unique(c(dt, scor))) == 1L)   # builder and every scoring script agree

rows <- list(c(
  "Inferential unit",
  "Stage-1 coherent clusters are tested; Stage-2 regions are assembled \\emph{post hoc}",
  sprintf("$%.2f\\times$ tests; recall $%+.3f$, never higher (%d worse, %d tied, %d better of %d)",
          sims_mult, sims_drec, sims_nlow, sims_ntie, sims_nhigh, nrow(w)),
  sprintf("$%.2f\\times$ tests; consensus discoveries $%d \\to %d$, Chr1 lost",
          pan_mult, pan$s1_cons_disc, pan$s2_cons_disc)),
  c("Stage-2 distance threshold",
    sprintf("\\texttt{distance\\_threshold} $=$ %s bp in \\texttt{ld\\_prune\\_and\\_eMLG}; identical in the bundle builder and all four scoring scripts", dt),
    "Nearly inert: LD blocks are short relative to either $1$e$5$ or $5$e$5$, so the simulations cannot discriminate",
    "Binds: at $5$e$5$, $120$ of $165$ \\emph{Eda} markers collapse into one $821$-marker, $18.4$~Mb group"))

## ---- emit --------------------------------------------------------------
hdr <- c(
  "% GENERATED by module_sim_LDscnR/make_table2.R -- do not edit by hand.",
  sprintf("%% Cross-check, computed just now: stage2/stage1 tests = %.4f (sims, %d paired panels)",
          sims_mult, nrow(w)),
  "% Panel column: ldscnr-2c, R_3sp_blocks/01_units_and_scan.R, floor 8, 300 kb lumping.",
  "\\begin{tabular}{p{2.6cm}p{4.6cm}p{3.7cm}p{3.7cm}}",
  "\\hline",
  "Choice & Frozen definition & Evidence: simulations & Evidence: stickleback panel \\\\",
  "\\hline")
body <- vapply(rows, function(r) paste0(paste(r, collapse = " & "), " \\\\"), character(1))
writeLines(c(hdr, body, "\\hline", "\\end{tabular}"), OUT)
cat(sprintf("wrote %s (%d row%s)\n", OUT, length(rows), if (length(rows) == 1) "" else "s"))
cat(sprintf("  sims  stage2/stage1 tests = %.3fx  (%s)\n", sims_mult,
            if (sims_mult < 1) "fewer" else "MORE"))
cat(sprintf("  panel stage2/stage1 tests = %.3fx  (%s)\n", pan_mult,
            if (pan_mult < 1) "fewer" else "MORE"))
