## =============================================================================
## module_3sp/R/12_table_regions.R
##
## Renders the primary EMMAX consensus scan's reported regions (03_EMMAX.R's
## scan.rds) as a LaTeX longtable, matching table5_sensitivity.tex's style
## (own \caption+\label, \input directly, NOT wrapped in \TableOrPlaceholder).
##
## REPLACES tables/table4_reported_regions.tex, which had been generated by
## the OLDER R_3sp_blocks/11_manuscript_figures.R pipeline and was stale
## against the current module_3sp scan (PK found this discrepancy 2026-09-05
## comparing against a from-scratch table build: e.g. the chromosome-1 region
## reported 32 clusters/1404 markers there against the current pipeline's 46
## units/1378 markers, and several Chr4/Chr7 region boundaries differed
## outright). Written to PATHS$tables, same "one place to browse before
## hand-picking" convention PATHS$figures and table5 already use.
## =============================================================================
suppressMessages({library(data.table)})
source(file.path(path.expand("~/gitlab/LDscnR-paper/module_3sp"), "R", "00_config.R"))
say("=== 12_table_regions ===\n\n")

SCAN_PATH <- file.path(PATHS$out, "03_EMMAX", "scan.rds")
sc <- readRDS(SCAN_PATH)
con <- sc$consensus

r <- copy(con$test$regions)
u <- copy(con$test$units)[significant == TRUE]
o <- copy(con$rotation$per_region)
setnames(o, "chr", "Chr")
setkey(o, Chr, from, to)
setkey(r, Chr, from, to)
r[, on_peak := o[.(Chr, from, to)]$on_peak]
r[, chr_num := as.integer(sub("Chr", "", Chr))]
## minimum unit-level q-value inside each region -- the strongest single piece of evidence
## supporting it, distinct from the region's own occupancy/EcoPeak columns.
r[, min_q := vapply(seq_len(.N), function(i) {
  min(u[Chr == r$Chr[i] & from >= r$from[i] & to <= r$to[i], q])
}, numeric(1))]
setorder(r, chr_num, from)

say("[1] %d regions, chr1--%d, %d on EcoPeaks\n", nrow(r), max(r$chr_num), sum(r$on_peak))

lines <- c(
  "% GENERATED by module_3sp/R/12_table_regions.R -- do not edit by hand.",
  "\\begin{longtable}{rrrrrrrlr}",
  paste0("\\caption{Regions assembled from significant Stage-1 units in the primary EMMAX ",
         "consensus analysis. Occupancy is the fraction of assayed markers inside the region ",
         "that belong to its constituent significant units.}",
         "\\label{tab:stickleback-regions}\\\\"),
  "\\hline",
  "Chr & Start (Mb) & End (Mb) & Span (kb) & Units & Markers & Occupancy & EcoPeak & Min. $q$ \\\\",
  "\\hline",
  "\\endfirsthead",
  "\\multicolumn{9}{l}{\\tablename~\\thetable{} continued}\\\\",
  "\\hline",
  "Chr & Start (Mb) & End (Mb) & Span (kb) & Units & Markers & Occupancy & EcoPeak & Min. $q$ \\\\",
  "\\hline",
  "\\endhead"
)
for (i in seq_len(nrow(r))) {
  x <- r[i]
  lines <- c(lines, sprintf(
    "%d & %.3f & %.3f & %.1f & %d & %d & %.3f & %s & %.3g \\\\",
    x$chr_num, x$from / 1e6, x$to / 1e6, (x$to - x$from) / 1e3,
    x$n_units, x$n_markers, x$occupancy,
    ifelse(x$on_peak, "yes", "--"), x$min_q))
}
lines <- c(lines, "\\hline", "\\end{longtable}")

OUT_TEX <- file.path(PATHS$tables, "table4_reported_regions.tex")
writeLines(lines, OUT_TEX)
say("[2] wrote %s\n", OUT_TEX)
say("\n    Placement: LDscnR_manuscript/Supplementary.tex, stickleback validation subsection,\n")
say("    landscape + \\scriptsize, \\input directly (longtable carries its own caption+label).\n")

write_receipt("12_table_regions", inputs = file.path(PATHS$out, "03_EMMAX", "_receipt.rds"),
             params = list(), outputs = OUT_TEX)
say("\n[3] receipt: %s\n", receipt_path("12_table_regions"))
