## =============================================================================
## module_3sp/R/13_goldilocks_units.R
##
## PORTED, not re-derived (PK, 2026-09-05): "the numbers exist already somewhere,
## you just need to pull out the correct code" -- Supplementary.tex's "intermediate
## complexity reduction as a Goldilocks solution" discussion already cites this
## analysis's numbers (99/102 matched-count units; eMLG consensus 13->4, centrality
## 11->3, Simes 10->4, highest-ld_w 9->1; median unit size 32->78), sourced from
## ~/gitlab/LD-pruning-paper/R_3sp/12_genomewide_units.R. This script is that
## analysis, relocated here for provenance and reproducibility, confirmed to
## reproduce EVERY cited number exactly on rerun (2026-09-05).
##
## [!] DELIBERATELY NOT REBASED ONTO module_3sp'S OWN BUNDLE. The source script's
## panel is NOT numerically identical to module_3sp's current one -- 616,497 vs
## 614,897 total Stage-1 clusters, confirmed by running both -- so silently
## swapping in this module's bundle would produce DIFFERENT numbers than the ones
## already accepted and cited in the manuscript, not a cleaner rerun of the same
## claim. This is an inherited-provenance dependency, the same category as
## 04_lfmm.R's lfmm_F.rds: the source data/cache lives in a different repository
## and is loaded as-is, not regenerated by this module. If the claim is ever
## rebuilt on module_3sp's own panel, that is a NEW analysis with its own numbers,
## not a refresh of this one.
##
## DEPENDENCIES (all in ~/gitlab/LD-pruning-paper, all confirmed present
## 2026-09-05):
##   - cache_3sp/map_only.rds, cache_3sp/K_eco.rds  -- per-marker EMMAX p-values/
##     positions and the GRM/ecotype vector, over the panel loaded from
##     3sp_data/3sp_LDscnR_data.rds (a symlink into LD-scaling-genome-scans).
##   - cache_3sp/stage2_Chr*_d1e+05.rds (20 files) -- genome-wide Stage-1 AND
##     Stage-2 partitions (R_3sp/07_3sp_stage2.R, DISTANCE_THRESHOLD = 1e5,
##     matching module_3sp's own canonical value -- see 00_config.R) plus the
##     stored eMLG consensus matrices.
##   - results_3sp/3sp_cmin_loci.csv -- the SUBSTITUTE truth set used only for
##     the loci-detected-at-Bonferroni cross-check (Kingman-EcoPeak-derived, not
##     module_3sp's own EcoPeak scan); a proxy, not ground truth (see the
##     original script's own header).
##
## WHAT THIS ANSWERS: at MATCHED test counts (~100 units each), does Stage-2
## whole-chromosome merging help or hurt detection, and does that differ by which
## representation is tested (Simes over all cluster members; the eMLG consensus
## dosage; the cluster's centrality/core-SNP representative; the member with
## highest local LD support ld_w; a random member as a chance baseline; the
## phenotype-informed min-p as an anticonservative upper bound, not a valid test)?
## c_min (the per-partition minimum cluster/group size) is swept to match each
## partition to ~100 span-capped (<=1000 kb) units, so the comparison isolates the
## effect of MERGING ITSELF from the effect of simply testing fewer, larger units.
## =============================================================================
suppressMessages({library(data.table); library(LDscnR)})
source(file.path(path.expand("~/gitlab/LDscnR-paper/module_3sp"), "R", "00_config.R"))
STAGE <- "13_goldilocks_units"
say("=== %s ===\n\n", STAGE)

LDPP <- path.expand("~/gitlab/LD-pruning-paper")
ALPHA <- 0.05; SEED <- 1L; SPAN_CAP <- 1e3; TARGET <- 100L; CGRID <- 2:400
BND <- path.expand("~/gitlab/LDscnR-paper/3sp_data/3sp_LDscnR_data.rds")
simes <- function(p) { p <- sort(p); min(length(p) * p / seq_along(p)) }

INPUTS <- c(file.path(LDPP, "cache_3sp", "map_only.rds"), file.path(LDPP, "cache_3sp", "K_eco.rds"),
           file.path(LDPP, "results_3sp", "3sp_cmin_loci.csv"))
PARAMS <- list(alpha = ALPHA, seed = SEED, span_cap = SPAN_CAP, target = TARGET, dthr = "1e5")
OUT_DIR <- file.path(PATHS$out, STAGE); dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)
if (!stage_stale(STAGE, INPUTS, PARAMS) && !nzchar(Sys.getenv("FORCE"))) {
  say("\nNothing to do. Set FORCE=1 to rerun anyway.\n"); quit(save = "no")
}

mm <- readRDS(file.path(LDPP, "cache_3sp", "map_only.rds")); pos <- mm$pos; pval <- mm$pval
ke <- readRDS(file.path(LDPP, "cache_3sp", "K_eco.rds")); K <- ke$K; eco <- ke$eco
fs <- sort(list.files(file.path(LDPP, "cache_3sp"), "^stage2_Chr[0-9]+_d1e\\+05\\.rds$", full.names = TRUE))
say("[0] %d chromosome caches at DTHR=1e5\n", length(fs))

## ---- 1. assemble both partitions genome-wide -------------------------------
S1 <- list(); S2 <- list(); EM <- list(); LDW <- list()
for (f in fs) {
  o  <- readRDS(f); ch <- sub(".*stage2_(Chr[0-9]+)_.*", "\\1", f)
  ms <- as.data.table(o$stage1$map_snp)
  LDW[[ch]] <- setNames(ms$ld_w_095, ms$marker)
  a <- copy(o$stage1$clusters); setnames(a, "n_snps", "n_loci", skip_absent = TRUE)
  a[, `:=`(Chr = ch, uid = paste0(ch, ":", CL_id), rep_snp = core_snp)]
  S1[[ch]] <- a[, .(Chr, uid, n_loci, rep_snp, members)]
  b <- as.data.table(o$res$groups)
  b[, `:=`(Chr = ch, uid = paste0(ch, ":", group_id), rep_snp = representative)]
  S2[[ch]] <- b[, .(Chr, uid, n_loci, rep_snp, members)]
  e <- o$res$eMLG
  if (!is.null(e) && NCOL(e)) { colnames(e) <- paste0(ch, ":", colnames(e)); EM[[ch]] <- e }
}
S1 <- rbindlist(S1); S2 <- rbindlist(S2); ldw <- unlist(LDW, use.names = FALSE)
names(ldw) <- unlist(lapply(LDW, names), use.names = FALSE)
EMLG <- do.call(cbind, EM)
say("[1] Stage 1: %s clusters ; Stage 2: %s groups ; consensus matrix %d x %d\n",
    format(nrow(S1), big.mark=","), format(nrow(S2), big.mark=","), nrow(EMLG), ncol(EMLG))

## integer-position resolution once per table (character indexing rebuilds a
## 790k-name hash per call -- the "hash trap" 3SP_RESULTS.md §G/I7 flags)
prep <- function(dt, lab) {
  dt <- dt[n_loci >= 2L]
  flat <- unlist(dt$members, use.names = FALSE)
  idx  <- split(match(flat, names(pval)), rep.int(seq_len(nrow(dt)), lengths(dt$members)))
  P <- unname(pval); Q <- unname(pos); W <- unname(ldw[names(pval)])
  dt[, start := vapply(idx, function(j) min(Q[j]), 0)]
  dt[, end   := vapply(idx, function(j) max(Q[j]), 0)]
  dt[, span_kb := (end - start) / 1e3]
  dt[, p_minp  := vapply(idx, function(j) min(P[j]), 0)]
  dt[, p_simes := vapply(idx, function(j) simes(P[j]), 0)]
  set.seed(SEED)
  dt[, p_rand  := vapply(idx, function(j) P[if (length(j) == 1L) j else sample(j, 1L)], 0)]
  dt[, p_ldw   := vapply(idx, function(j) P[j[which.max(W[j])]], 0)]
  dt[, p_centr := unname(pval[rep_snp])]
  dt[, .idx := idx]
  say("[1] %s prepared: %s units with >=2 markers\n", lab, format(nrow(dt), big.mark=","))
  dt
}

## D1's diagnostic: where does each chooser's SNP sit in its own cluster's
## p-value ranking? (1 = best of n.) Computed only on the retained (post-c_min)
## units -- match() per row over 790k names is the hash trap again if done earlier.
add_ranks <- function(k) {
  P <- unname(pval); W <- unname(ldw[names(pval)])
  ri <- match(k$rep_snp, names(pval))
  k[, rk_ldw   := vapply(seq_len(.N), function(i) { j <- .idx[[i]]
                    sum(P[j] <= P[j[which.max(W[j])]]) }, 0L)]
  k[, rk_centr := vapply(seq_len(.N), function(i) { j <- .idx[[i]]
                    sum(P[j] <= P[ri[i]]) }, 0L)]
  k[]
}
U1 <- prep(S1, "Stage 1"); U2 <- prep(S2, "Stage 2")

## ---- 2. pick c_min per partition for ~TARGET units, apply the span cap ------
pick <- function(u) { sz <- vapply(CGRID, function(k) sum(u$n_loci >= k & u$span_kb <= SPAN_CAP), 0L)
                      CGRID[which.min(abs(sz - TARGET))] }
c1 <- pick(U1); c2 <- pick(U2)
K1 <- add_ranks(U1[n_loci >= c1 & span_kb <= SPAN_CAP])
K2 <- add_ranks(U2[n_loci >= c2 & span_kb <= SPAN_CAP])
say("\n[2] Stage 1: c_min = %d -> %d units ; Stage 2: c_min = %d -> %d units\n",
    c1, nrow(K1), c2, nrow(K2))

## ---- 3. the consensus unit --------------------------------------------------
## Stage 2: consensus already built by ld_prune_and_eMLG(). Stage 1: build it with
## make_eMLGs() straight from the per-marker cluster assignment (no Stage 2 needed).
K2[, has_c := uid %in% colnames(EMLG)]
E2 <- EMLG[, K2[has_c == TRUE, uid], drop = FALSE]
E2 <- E2[, apply(E2, 2, function(z) stats::sd(z, na.rm = TRUE) > 0), drop = FALSE]
p2 <- emmax_fast(emmax_setup(E2, K), eco); names(p2) <- colnames(E2)
K2[, p_emlg := unname(p2[uid])]

GTS_CACHE <- file.path(LDPP, "cache_3sp", "GTs_s1units.rds")
if (!file.exists(GTS_CACHE)) {
  d <- readRDS(BND); mk <- unique(unlist(K1$members, use.names = FALSE))
  saveRDS(d$GTs[, mk, drop = FALSE], GTS_CACHE); rm(d); gc()
}
G1 <- readRDS(GTS_CACHE)
mc <- rbindlist(lapply(seq_len(nrow(K1)), function(i)
        data.table(marker = K1$members[[i]], CL_id = K1$uid[i], n_loci = K1$n_loci[i])))
mc[, `:=`(Chr = sub(":.*", "", CL_id), Pos = pos[marker])]
e1 <- make_eMLGs(G1[, mc$marker, drop = FALSE], map_cl = mc, l_min = 2L, ncores = 1)
E1 <- if (is.matrix(e1)) e1 else e1$eMLG
E1 <- E1[, intersect(K1$uid, colnames(E1)), drop = FALSE]
E1 <- E1[, apply(E1, 2, function(z) stats::sd(z, na.rm = TRUE) > 0), drop = FALSE]
p1 <- emmax_fast(emmax_setup(E1, K), eco); names(p1) <- colnames(E1)
K1[, p_emlg := unname(p1[uid])]
say("[3] consensus available for %d/%d Stage-1 and %d/%d Stage-2 units\n",
    sum(!is.na(K1$p_emlg)), nrow(K1), sum(!is.na(K2$p_emlg)), nrow(K2))

## ---- 4. detection, and the D1 rank diagnostic -------------------------------
UN <- c("minp","simes","emlg","rand","ldw","centr")
UN_LAB <- c(minp = "min-p (uses phenotype)", simes = "Simes", emlg = "eMLG consensus",
           rand = "random member", ldw = "highest ld\\_w", centr = "centrality")
summarise_partition <- function(k, lab) { n <- nrow(k); bonf <- ALPHA / n
  say("\n=== %s : %d units (c_min per partition) ; Bonferroni = %.2e ===\n", lab, n, bonf)
  tb <- rbindlist(lapply(UN, function(v) { p <- k[[paste0("p_", v)]]; p <- p[!is.na(p)]
    data.table(partition = lab, unit = v, uses_phenotype = v == "minp", n_with_p = length(p),
               min_p = signif(min(p), 3), sig_bonf = sum(p <= bonf),
               sig_bh = sum(p.adjust(p, "BH") <= ALPHA), median_p = signif(median(p), 3)) }))
  print(tb)
  say("  D1 diagnostic: median within-unit rank -- ld_w %.0f, centrality %.0f, of median n = %.0f\n",
      median(k$rk_ldw), median(k$rk_centr), median(k$n_loci))
  tb[, `:=`(bonferroni = bonf, median_rk_ldw = median(k$rk_ldw), median_rk_centr = median(k$rk_centr),
           median_n = median(k$n_loci))]
}
TAB1 <- summarise_partition(K1, "Stage 1")
TAB2 <- summarise_partition(K2, "Stage 2")
SUMMARY <- rbind(TAB1, TAB2)

## ---- 5. against the (substitute) truth set ----------------------------------
L <- fread(file.path(LDPP, "results_3sp", "3sp_cmin_loci.csv"))
score <- function(k, lab) { n <- nrow(k); bonf <- ALPHA / n
  k2 <- copy(k)[, chr_num := as.integer(gsub("Chr", "", Chr))]
  KK <- k2[, c("chr_num","start","end", paste0("p_", UN)), with = FALSE]; setkey(KK, chr_num, start, end)
  ov <- foverlaps(L[, .(chr_num, start, end, locus)], KK,
                  by.x = c("chr_num","start","end"), type = "any", nomatch = NA)
  r <- ov[, lapply(.SD, function(z) suppressWarnings(min(z, na.rm = TRUE))), by = locus,
          .SDcols = paste0("p_", UN)]
  r <- merge(L[, .(locus, lab2 = lab, ntot, KGlob, KPac)], r, by = "locus")
  cnt <- function(sub) vapply(UN, function(v) sum(is.finite(sub[[paste0("p_",v)]]) &
                                sub[[paste0("p_",v)]] <= bonf), 0L)
  rbindlist(list(
    data.table(partition = lab, set = "all loci", n = nrow(r),
               in_part = sum(is.finite(r$p_minp)), t(cnt(r))),
    data.table(partition = lab, set = "corroborated >=2", n = sum(r$ntot >= 2),
               in_part = sum(is.finite(r$p_minp) & r$ntot >= 2), t(cnt(r[ntot >= 2]))),
    data.table(partition = lab, set = "Kingman-supported", n = sum(r$KGlob | r$KPac),
               in_part = sum(is.finite(r$p_minp) & (r$KGlob | r$KPac)),
               t(cnt(r[KGlob | KPac])))))
}
TRUTHSET <- rbind(score(K1, "Stage 1"), score(K2, "Stage 2"))
say("\n[5] loci detected at Bonferroni, by partition and unit (PROXY truth set)\n")
print(TRUTHSET)

## ---- 6. LaTeX table (matches table5_sensitivity.tex's longtable style) -----
lines <- c(
  "% GENERATED by module_3sp/R/13_goldilocks_units.R -- do not edit by hand.",
  "\\begin{longtable}{llrrrrrr}",
  paste0("\\caption{Six phenotype-blind and phenotype-informed representations of the same ",
         "Stage-1/Stage-2 cluster, tested genome-wide at matched test counts (span-capped ",
         "$\\le$1 Mb, minimum cluster size swept to $\\approx$100 units per partition). ",
         "Min-p uses the phenotype to choose its member and is an anticonservative reference, ",
         "not a valid test; the random member is a chance baseline.}",
         "\\label{tab:goldilocks-units}\\\\"),
  "\\hline",
  "Partition & Unit & Tested & Min. $p$ & Sig. (Bonf.) & Sig. (BH) & Median $p$ & Median rank/$n$ \\\\",
  "\\hline",
  "\\endfirsthead",
  "\\multicolumn{8}{l}{\\tablename~\\thetable{} continued}\\\\",
  "\\hline",
  "Partition & Unit & Tested & Min. $p$ & Sig. (Bonf.) & Sig. (BH) & Median $p$ & Median rank/$n$ \\\\",
  "\\hline",
  "\\endhead"
)
for (lab in c("Stage 1", "Stage 2")) {
  rows <- SUMMARY[partition == lab]
  for (i in seq_len(nrow(rows))) {
    r <- rows[i]
    part_cell <- if (i == 1) lab else ""
    rank_cell <- if (r$unit == "ldw") sprintf("%.0f / %.0f", r$median_rk_ldw, r$median_n)
                else if (r$unit == "centr") sprintf("%.0f / %.0f", r$median_rk_centr, r$median_n)
                else sprintf("-- / %.0f", r$median_n)
    lines <- c(lines, sprintf("%s & %s & %d & %s & %d & %d & %s & %s \\\\",
      part_cell, UN_LAB[r$unit], r$n_with_p, sprintf("%.2e", r$min_p), r$sig_bonf, r$sig_bh,
      sprintf("%.3g", r$median_p), rank_cell))
  }
  lines <- c(lines, "\\hline")
}
lines <- c(lines, "\\end{longtable}")
OUT_TEX <- file.path(PATHS$tables, "table6_goldilocks_units.tex")
writeLines(lines, OUT_TEX)
say("\n[6] wrote %s\n", OUT_TEX)

## ---- 7. save + receipt -------------------------------------------------------
OUT_RDS <- file.path(OUT_DIR, "goldilocks_units.rds")
saveRDS(list(c1 = c1, c2 = c2, summary = SUMMARY, truthset = TRUTHSET,
            K1 = K1[, .(uid, Chr, start, end, span_kb, n_loci, p_minp, p_simes, p_emlg, p_rand, p_ldw, p_centr)],
            K2 = K2[, .(uid, Chr, start, end, span_kb, n_loci, p_minp, p_simes, p_emlg, p_rand, p_ldw, p_centr)]),
        OUT_RDS)
write_receipt(STAGE, inputs = INPUTS, params = PARAMS, outputs = c(OUT_RDS, OUT_TEX))
say("\n[7] wrote %s\n    receipt: %s\n", OUT_RDS, receipt_path(STAGE))
