library(data.table)
library(effectsize)
library(scales)
library(tidyr)
library(knitr)
library(pracma)
library(factoextra)
library(parallel)
library(wesanderson)
library(LEA)
library(egg)
library(igraph)
library(dplyr)
library(SNPRelate)
library(stats)
library(ggplot2)
library(data.table)
library(ggplot2)
library(ggsci)
library(LDscnR)
source("./R/emmax.R")

### --- Get focal QNT for a given SNP --- ###
#   gds - gds file generated by SNPrelate
#   map - The corresponding map file that contains at least columns "marker"
#     "and "type" where type=="QTN" are the potential focal QTN


focal_QTN <- function(gds, map, qtn_col = "true_QTN") {

  ids <- .read_gds_ids(gds)
  #ch = "Chr1"
  rbindlist(lapply(unique(ids$snp_chr), function(ch) {

    idx_chr <- which(ids$snp_chr == ch)

    snp_ids_chr <- ids$snp_id[idx_chr]

    # map rows on this chromosome, restricted to SNPs present in GDS
    map_chr <- map[Chr == ch & marker %in% snp_ids_chr]

    markers_chr <- map_chr$marker

    qtn_chr <- map_chr[get(qtn_col) == TRUE, marker]

    if (length(qtn_chr) == 0L) {
      return(data.table(
        Chr = ch,
        marker = markers_chr,
        max_LD_with_QTN = 0,
        focal_QTN = NA_character_,
        bp_to_focal_QTN = NA_real_
      ))
    }


    r2 <- cor(GTs[, qtn_chr], GTs[,markers_chr],use = "pairwise.complete.obs")^2

    max_ld <- apply(r2, 2, max, na.rm = TRUE)
    focal_idx <- max.col(t(r2), ties.method = "first")
    focal_qtn <- qtn_chr[focal_idx]

    pos_vec <- map_chr$Pos
    names(pos_vec) <- map_chr$marker

    data.table(
      Chr = ch,
      marker = markers_chr,
      max_LD_with_QTN = max_ld,
      focal_QTN = focal_qtn,
      bp_to_focal_QTN = abs(pos_vec[markers_chr] - pos_vec[focal_qtn])
    )

  }), fill = TRUE)
}





simulate_quant_pheno <- function(K, h2 = 0.5, nrep = 1, scale_K = TRUE,
                                 mean = 0, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)
  if (!requireNamespace("MASS", quietly = TRUE)) {
    stop("Please install MASS: install.packages('MASS')")
  }

  K <- as.matrix(K)
  n <- nrow(K)

  if (scale_K) {
    K <- K / mean(diag(K))
  }

  V <- h2 * K + (1 - h2) * diag(n)

  Y <- MASS::mvrnorm(
    n = nrep,
    mu = rep(mean, n),
    Sigma = V
  )

  if (nrep == 1) {
    Y <- matrix(Y, ncol = 1)
  } else {
    Y <- t(Y)  # SNP/individual order: individuals x replicates
  }

  rownames(Y) <- rownames(K)
  colnames(Y) <- paste0("sim_", seq_len(nrep))

  Y
}

LD_igraph_components <- function(GTs, map, markers, r2_th = 0.8, bp_th = Inf,full=FALSE) {
  gts <- as.matrix(GTs[,markers])
  storage.mode(gts) <- "double"

  stopifnot(all(colnames(gts) %in% map$marker))

  # order map to match genotype columns
  snp_map <- map[match(colnames(gts), marker)]

  # fast LD matrix

  R2 <- cor(gts, use = "pairwise.complete.obs")^2
  R2[is.na(R2)] <- 0

  # candidate SNP pairs above LD threshold
  idx <- which(R2 >= r2_th, arr.ind = TRUE)
  idx <- idx[idx[, 1] < idx[, 2], , drop = FALSE]

  edges <- data.table(
    from = colnames(gts)[idx[, 1]],
    to   = colnames(gts)[idx[, 2]],
    r2   = R2[idx]
  )

  # optional physical-distance filter
  if (is.finite(bp_th)) {
    pos <- snp_map$Pos
    chr <- snp_map$Chr

    edges[, `:=`(
      Chr_from = chr[match(from, colnames(gts))],
      Chr_to   = chr[match(to, colnames(gts))],
      dist_bp  = abs(pos[match(from, colnames(gts))] -
                       pos[match(to, colnames(gts))])
    )]

    edges <- edges[Chr_from == Chr_to & dist_bp <= bp_th]
  }

  g <- graph_from_data_frame(
    edges[, .(from, to)],
    directed = FALSE,
    vertices = data.table(name = colnames(gts))
  )

  comp <- components(g)

  clusters <- data.table(
    marker = names(comp$membership),
    CL_id = as.integer(comp$membership)
  )

  clusters[, n_loci := comp$csize[CL_id]]

  if(full){
    list(
      graph = g,
      edges = edges,
      clusters = clusters,
      components = comp
    )
  }else{
    clusters
  }


}
d_from_rho <- function (a, rho)
{
  rho/(a * (1 - rho))
}

ld_from_rho <- function (b, c = 1, rho)
{
  b + (c - b) * (1 - rho)
}

.read_gds_ids <- function(gds) {
  list(
    snp_id  = gdsfmt::read.gdsn(gdsfmt::index.gdsn(gds, "snp.id")),
    snp_chr = gdsfmt::read.gdsn(gdsfmt::index.gdsn(gds, "snp.chromosome")),
    snp_pos = gdsfmt::read.gdsn(gdsfmt::index.gdsn(gds, "snp.position"))
  )
}
# parsed files generated by ./R_simulations/Parse_raw_data_sim.R
files <- list.files("../LD-scaling-genome-scans/parsed_data/",full.names = TRUE)

#files <- files[grep("V0.5_c1_rep4",files)]

# split them into replicates (n=10) with the same landscape but different recombination maps, here only one replicate is provided (full data from Zenondo)
tmp <- do.call(rbind,strsplit(files,"/",fixed=TRUE))[,5]

files_split <- split(files, gsub(".rds","",apply(do.call(rbind,strsplit(tmp,"_",fixed=TRUE))[,2:4],1,paste,collapse="_")))

out_folder <- "../LD-scaling-genome-scans/parsed_data/"
min_maf <- 0.1

# These are the pre-drawn individuals used for all
# Note that the parsed data contains data for 500 individuals, and these are a subsample of those
keep_125 <-readRDS("../LD-scaling-genome-scans/data/keep_inds_125.rds")
cores <- 8 # cores to use

# fil <- files_split[[5]]
#if(TRUE){
  message("\n\n#### ==== Starting outlier analyses ==== ####\n\n")

fil <- files_split[[1]]
#for(fil in files_split){

# ------------------------ #
# Read in and prepare data
# ------------------------ #

## read in data
data <- lapply(fil, function(file) readRDS(file))
map <- do.call(rbind,lapply(data,function(x)x$map))

## only if result file does not exist
#if(!file.exists(paste0(out_folder,paste(map[1,.(c,V,rep)],collapse="_"),".rds"))){

GTs <- do.call(cbind,lapply(data,function(x)x$GTs))



#re-label chromosomes since we are concatenating data from 10 replicates
new_order <- map[,order(Chr_9sp,-as.numeric(factor(Chr_type)))]
GTs <- GTs[,new_order]
setorder(map,Chr_9sp,Chr_type)

levs <- map[!duplicated(paste(Chr_9sp,Chr_type))][,paste(Chr_9sp,Chr_type)]
map[,LG:=as.numeric(factor(paste(Chr_9sp,Chr_type),levels=levs))]
map[,Chr:=paste0("Chr",LG)]
map[,marker:=paste(Chr,bp,sep=":")]
setnames(map,"bp","Pos")
colnames(GTs) <- map$marker
env_ind <- data[[1]]$env[keep_125]
env <- data[[1]]$env$env

## subsample -> reduce from 500 to 125 individuals
env <- env[keep_125]
GTs <- GTs[keep_125,]

## remove duplicate loci
GTs <- GTs[,map[,which(!duplicated(marker))]]
map <- map[!duplicated(marker)]

## recalculate maf for the subsample and filter anew

maf_new <- colSums(GTs)/nrow(GTs)/2
maf_new <- ifelse(maf_new<0.5,maf_new,1-maf_new)
map[,maf:=maf_new]
GTs <- GTs[,maf_new>min_maf]
map <- map[maf>min_maf]





## generate gds file
gds_path = tempfile(fileext = ".gds")
gds <- create_gds_from_geno(geno = GTs,map=map,gds_path)

## close at exit
on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE)

ids <- .read_gds_ids(gds)

qtn_rows <- map[,which(type=="QTN")]
## compute Va
va <- sapply(qtn_rows, function(i){
  a  <- map$allelic_values[i]               # effect size α
  gt <- GTs[, i, drop=TRUE]                 # genotype 0/1/2
  p  <- mean(gt)/2                          # allele frequency
  2 * p * (1 - p) * a^2                     # Va formula
})

## assign
map[qtn_rows, Va := va]

## total Va per chromosome
map[qtn_rows, sum_Va := sum(Va), by = Chr_9sp]

## proportion
map[qtn_rows, p_Va := Va / sum_Va]

ld_decay <- compute_LD_decay(
  gds=gds,
  el_data_folder = NULL,
  n_win_decay = 20,
  max_SNPs_decay = Inf,
  keep_el = TRUE,
  slide=1000,
  cores = 8,
  ld_method = "r"
)

## add decay info to map
as <- setNames(ld_decay$decay_sum$a_pred,ld_decay$decay_sum$Chr)
bs <- setNames(ld_decay$decay_sum$b,ld_decay$decay_sum$Chr)
cs <- setNames(ld_decay$decay_sum$c_pred,ld_decay$decay_sum$Chr)
map[,a := as[Chr]]
map[,b := bs[Chr]]
map[,c := cs[Chr]]

# ---------------------------------- #
# Get focal QTN and associated data
# ---------------------------------- #
message("Get focal QTN \n")

map[type == "QTN" & p_Va >= 0.05 & maf>0.1,true_QTN := TRUE]

true_qtns <- map[true_QTN == TRUE, marker]
fq <- focal_QTN(gds, map, qtn_col = "true_QTN")

map[fq, on = "marker",
    `:=`(
      focal_QTN = i.focal_QTN,
      bp_to_focal_QTN = i.bp_to_focal_QTN,
      max_LD_with_QTN = i.max_LD_with_QTN
    )]

## collect data
map[type == "QTN", `:=`(
  focal_QTN = marker,
  max_LD_with_QTN = 1,
  bp_to_focal_QTN = 0
)]
map[Chr_type=="ntrl",bp_to_focal_QTN:=max(Pos)]
map[Chr_type=="ntrl",max_LD_with_QTN:=0]

map[, rho_d := a * bp_to_focal_QTN / (a * bp_to_focal_QTN + 1)]
map[, ld_rel := (max_LD_with_QTN - b) / (c - b)]
map[, ld_rel := pmin(pmax(ld_rel, 0), 1)]

map[, true_pos := rho_d < 0.75 & ld_rel > 0.5]



ld_ws <- precalculate_ld_w(c(seq(0.2,0.95,by=0.05),0.99),ld_decay)

#map <- copy(map_org)

#env <- as.vector(simulate_quant_pheno(K=GRM, h2 = 0, nrep = 1))

for(ch in unique(map$Chr_9sp)){
  idx <- which(map$Chr_9sp==ch)
  GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm

  ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
  emx <- emmax(env,GTs[,idx],K = GRM)

  map[idx,emx_F:=emx$F] ## add to map
  emx_gif = map[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
  map[idx,emx_F:=emx_F/emx_gif]  ## genomic control

  ### === Latent factor mixed model analyses (LFMM) === ###

  ## get K
  xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
  results <- xxx.pca1$x
  km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)

  ## LFMM
  write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
  write.env(env, "./tmp/gradients.env")
  project = NULL

  project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
  pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))

  ## save F-value corrected for inflation
  map[idx,lfmm_F:=pv$fscores/pv$gif]
}


map[,lfmm_p := pf(lfmm_F,1,115,lower.tail = FALSE)]
map[,emx_p := pf(emx_F,1,115,lower.tail = FALSE)]
map[,lfmm_q := p.adjust(lfmm_p,"fdr")]
map[,emx_q := p.adjust(emx_p,"fdr")]








#
map[,ld_w := ld_ws[,"0.5"]]
map[, indx := .I]

rho_ld_grid = c(seq(0.2, 0.95, by = 0.1), 0.99)

qt_grid <- c(seq(0.2, 0.95, by = 0.05), 0.99)

alpha_grid <- -log10(c(
  0.05,
  0.01,
  0.005,
  0.001,
  0.0005,
  0.0001
))

l_min_grid <- seq(0,10,by=2)
rho_grid <- colnames(ld_ws)

# full parameter combinations
param_grid <- CJ(
  qt = qt_grid,
  alpha = alpha_grid,
  rho = rho_grid,
  rho_ld_grid
)

max_gap = 1e6
i <- 1
res <- rbindlist(mclapply(seq_len(nrow(param_grid)), function(i) {
  #print(i)
  pars <- param_grid[i]

  qt <- pars$qt
  alpha <- pars$alpha
  rho <- pars$rho
  rho_ld <- pars$rho_ld

  map_sub <- map[ld_ws[,rho]>quantile(ld_w,qt,na.rm=TRUE)]
  map_sub[,lfmm_q := -log10(p.adjust(pf(lfmm_F,1,115,lower.tail = FALSE),"fdr"))]
  peaks <- map_sub[lfmm_q>alpha, .(Chr, marker, Pos)]

  peaks[, peak_cluster := cumsum(is.na(Pos - shift(Pos)) | (Pos - shift(Pos)) > max_gap),by = Chr]
  peaks[, phy_uid := paste0(Chr, "_phy", peak_cluster)]

  phy_cls <- split(peaks$marker, peaks$phy_uid)

  if(length(phy_cls)>0){
    sl_cls <- rbindlist(parallel::mclapply(seq_along(phy_cls), function(cl) {
      #print(cl)
      markers_cl <- phy_cls[[cl]]

      ld_decay$decay_sum

      ch <- map[marker %in% markers_cl,Chr[1]]


      # thresholds

      c_chr  <- ld_decay$decay_sum[Chr == ch, c_pred]

      ld_th <- ld_from_rho(b_chr, c_chr, rho = rho_ld)

      if (length(markers_cl) > 1) {
        out <- LD_igraph_components(
          GTs,
          map,
          markers = markers_cl,
          r2_th = 0.6,
          bp_th = Inf,
          full = FALSE
        )
      } else {

        out <- data.table(
          marker = markers_cl,
          CL_id = 1L,
          n_loci = 1L
        )
      }

      out[, phy_cl := cl]

      # globally unique cluster name
      out[, CL_uid := paste0("phy", phy_cl, "_ld", CL_id)]

      out

    }, mc.cores = 1))

    out <- data.table(ld_th,qt,alpha,rho,l_min=l_min_grid,OR=list(lapply(l_min_grid,function(l_min){
      mrk <- sl_cls[n_loci>l_min,marker]

      if(length(mrk)>0) mrk else NULL
    })))

  }else{
    out <- data.table(ld_th,qt,alpha,rho,l_min=l_min_grid,OR=list())
  }
  out

},mc.cores=cores))
res$OR_size <- sapply(res$OR,length)

C_scores <- table(unlist(res$OR))/nrow(res)

C_scores <- data.table(marker=names(C_scores),C=as.vector(C_scores))


#C_scores
map[C_scores, on = "marker",
    `:=`(
      C = i.C
    )]

map[is.na(C),C:=0]

map[,plot(C,pch=ifelse(type=="QTN",3,20),cex=ifelse(type=="QTN",2,0.5))]
map[,plot(-log10(lfmm_q),pch=ifelse(type=="QTN",3,20),cex=ifelse(type=="QTN",2,0.5))]
abline(h=1.3)





      map[!is.na(CL_uid)]
      map[lfmm_q<(1/10^alpha),]

      abline(h=1.3,col="steelblue")


      draws_obs_per_meth <- ld_rho_draws(gds,
                                         ld_decay  = ld_decay,
                                         F_vals     = map[,.(lfmm_F,emx_F)], ## the F values are pre-calculated and must be provided, these will be used for getting F_prime.
                                         q_vals     = NULL, ## q-values from original analyses can also be used but not necessary
                                         n_draws    = 100,
                                         stat_type  = "q",
                                         rho        = NULL, ## grid of rho values used for ld_w
                                         ld_ws      = ld_ws,
                                         rho_d_lim  = list(min=0.5,max=0.99),
                                         rho_ld_lim = list(min=0.5,max=0.99),
                                         alpha_lim  = list(min=0.3,max=4), ## lowest alpha is 1/10^0.6=0.25; this range is defined in the -log10 scale!
                                         lmin_lim   = list(min=1,max=10),
                                         cores      = 8,
                                         mode       = c("per_method")
      )

      draws_joint_obs <- ld_rho_draws(gds,
                                      ld_decay  = ld_decay,
                                      F_vals     = map[,.(lfmm_F,emx_F)], ## the F values are pre-calculated and must be provided, these will be used for getting F_prime.
                                      q_vals     = map[,.(lfmm_q,emx_q)], ## q-values from original analyses can also be used but not necessary
                                      n_draws    = 100,
                                      stat_type  = "q",
                                      rho        = NULL, ## grid of rho values used for ld_w
                                      ld_ws      = ld_ws,
                                      rho_d_lim  = list(min=0.5,max=0.99),
                                      rho_ld_lim = list(min=0.5,max=0.99),
                                      alpha_lim  = list(min=1.3,max=4), ## lowest alpha is 1/10^0.6=0.25; this range is defined in the -log10 scale!
                                      lmin_lim   = list(min=1,max=10),
                                      cores      = 8,
                                      mode       = c("joint")
      )

      map_obs <- copy(map)
      map_obs <- add_consistency_to_map(map_obs, consistency_obj = consistency_score(draws_joint_obs$draws[method=="Joint"]))

      map_obs[,]
      #### permuted phenotype


      simulate_quant_pheno <- function(K, h2 = 0.5, nrep = 1, scale_K = TRUE,
                                       mean = 0, seed = NULL) {
        if (!is.null(seed)) set.seed(seed)
        if (!requireNamespace("MASS", quietly = TRUE)) {
          stop("Please install MASS: install.packages('MASS')")
        }

        K <- as.matrix(K)
        n <- nrow(K)

        if (scale_K) {
          K <- K / mean(diag(K))
        }

        V <- h2 * K + (1 - h2) * diag(n)

        Y <- MASS::mvrnorm(
          n = nrep,
          mu = rep(mean, n),
          Sigma = V
        )

        if (nrep == 1) {
          Y <- matrix(Y, ncol = 1)
        } else {
          Y <- t(Y)  # SNP/individual order: individuals x replicates
        }

        rownames(Y) <- rownames(K)
        colnames(Y) <- paste0("sim_", seq_len(nrep))

        Y
      }

      Y <- simulate_quant_pheno(K=GRM, h2 = 0, nrep = 100)

      indx <- 0
      perm_F_prime <- list()
      perm_F_x_ld_w <- list()
      x <- 1
      perm_F <- mclapply(1:ncol(Y),function(x){
        print(x)
        map_perm <- copy(map_org)

        for(ch in unique(map_perm$Chr_9sp)){
          idx <- which(map_perm$Chr_9sp==ch)
          GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm

          ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
          emx <- emmax(Y[,x],GTs[,idx],K = GRM)

          map_perm[idx,emx_F:=emx$F] ## add to map_perm
          emx_gif = map_perm[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
          map_perm[idx,emx_F:=emx_F/emx_gif]  ## genomic control

          ### === Latent factor mixed model analyses (LFMM) === ###

          # ## get K
          # xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
          # results <- xxx.pca1$x
          # km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)
          #
          # ## LFMM
          # write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
          # write.env(Y[,x], "./tmp/gradients.env")
          # project = NULL
          #
          # project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
          # pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))
          #
          # ## save F-value corrected for inflation
          # map_perm[idx,lfmm_F:=pv$fscores/pv$gif]
        }
        map_perm$emx_F

      },mc.cores=8)

      perm_F_lfmm <- mclapply(1:ncol(Y),function(x){
        print(x)
        map_perm <- copy(map_org)

        for(ch in unique(map_perm$Chr_9sp)){
          idx <- which(map_perm$Chr_9sp==ch)
          # GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm
          #
          # ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
          # emx <- emmax(Y[,x],GTs[,idx],K = GRM)
          #
          # map_perm[idx,emx_F:=emx$F] ## add to map_perm
          # emx_gif = map_perm[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
          # map_perm[idx,emx_F:=emx_F/emx_gif]  ## genomic control

          ### === Latent factor mixed model analyses (LFMM) === ###

          ## get K
          xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
          results <- xxx.pca1$x
          km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)

          ## LFMM
          write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
          write.env(Y[,x], "./tmp/gradients.env")
          project = NULL

          project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
          pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))

          ## save F-value corrected for inflation
          map_perm[idx,lfmm_F:=pv$fscores/pv$gif]
        }
        map_perm$lfmm_F

      },mc.cores=1)
      perm_F_lfmm <- do.call(cbind, perm_F_lfmm)

      lfmm_q_perm <- sapply(1:100,function(x){
        length(which(p.adjust(pf(perm_F_lfmm[,x],1,124,lower.tail = FALSE),"fdr")<0.05))
      })
      #lfmm_q_perm

      emx_q_perm <- sapply(1:100,function(x){
        length(which(p.adjust(pf(perm_F[,x],1,124,lower.tail = FALSE),"fdr")<0.05))
      })
      which(emx_q_perm>0)
      plot(-log10(p.adjust(pf(perm_F[,92],1,124,lower.tail = FALSE),"fdr")))

      plot(perm_F[,x])
      plot(-log10(qf(perm_F[,x],1,124,lower.tail = FALSE)))
      p.adjust(qf(perm_F[,x],1,124,lower.tail = FALSE),"fdr")

      emx_q_perm
      tmp <- lapply(1:100,function(x){
        print(x)
        perm_F[,x]*ld_w-apply(perm_F[,-x]*ld_w, 1, quantile, probs = 0.95, na.rm = TRUE)
      })

      resid_q95 <- map$emx_F*ld_w - apply(perm_F*ld_w, 1, quantile, probs = 0.95, na.rm = TRUE)
      x <- 3
      resid_q95_perm <- perm_F[,x]*ld_w-apply(perm_F[,-x]*ld_w, 1, quantile, probs = 0.95, na.rm = TRUE)
      plot(resid_q95)
      abline(h=quantile(unlist(tmp),0.999,na.rm = TRUE))
      plot(resid_q95_perm)
      abline(h=quantile(unlist(tmp),0.999,na.rm = TRUE))


      th <- quantile(unlist(tmp),0.999,na.rm = TRUE)

      which(sapply(tmp,function(x) length(which(x>th)))>50)

      ymp <- do.call(rbind,lapply(perm_F,function(x) x*ld_w))
      perm_95 <- apply(ymp,2,quantile, 0.95,na.rm=TRUE)
      quantile(ymp,0.9,na.rm = TRUE)
      plot(map$emx_F*ld_w)
      plot(ymp[3,])
      abline(h=quantile(ymp,0.99,na.rm = TRUE))

      max(perm_95,na.rm = TRUE)
      max(map$emx_F*ld_w,na.rm = TRUE)
      resid_q95_ldw  <- perm_F[[3]]*ld_w - perm_95
      resid_q95_ldw[resid_q95_ldw<0] <- 0
      plot(resid_q95_ldw, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")


      plot(resid_q95)
      plot(map$emx_F*ld_w-apply(ymp,2,quantile, 0.99,na.rm=TRUE))

      lapply(perm_F_prime,function(x) x[,1])


      tmp <- do.call(cbind, lapply(perm_F_prime,function(x) x[,1]))
      dim(tmp)

      conf <- apply(do.call(cbind, lapply(perm_F_prime,function(x) x[,1])), 1, quantile, 0.95,na.rm=TRUE)

      emx_prime <- compute_Fprime(map$emx_F, ld_ws[,1], 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      tmp <- emx_prime-conf
      tmp[tmp<0] = 0


      Fperm <- do.call(cbind, lapply(perm_F_prime,function(x) x[,1]))
      q95 <- apply(Fperm[, ], 1, quantile, 0.95,na.rm=TRUE)

      p_emp <- (1 + rowSums(Fperm >= emx_prime)) / (1 + ncol(Fperm))

      perm_mean <- rowMeans(Fperm)
      perm_q95  <- apply(Fperm, 1, quantile, probs = 0.95, na.rm = TRUE)
      perm_q99  <- apply(Fperm, 1, quantile, probs = 0.99, na.rm = TRUE)

      F_obs <- Fperm[,2]
      F_obs <- emx_prime
      plot(emx_prime)
      abline(h=quantile(Fperm,0.999,na.rm = TRUE))

      hist(Fperm)

      F_obs <- emx_prime
      resid_q95  <- F_obs - perm_q95
      resid_q95[resid_q95<0] <- 0
      plot(resid_q95, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")

      plot(resid_q95,resid_q95_ldw*10)
      abline(0,1)


      max_res_perm <- lapply(1:ncol(Fperm),function(x){
        print(x)
        max(Fperm[,x]-apply(Fperm[,-x], 1, quantile,0.95, na.rm = TRUE),na.rm = TRUE)
      })

      which(unlist(max_res_perm)>50)
      quantile(unlist(max_res_perm),0.95)




      plot(apply(do.call(cbind, max_res_perm),1,quantile, 0.95,na.rm=TRUE))

      hist(max_res_perm)


      abline(h=quantile(Fperm,0.999,na.rm = TRUE))


      tmp_prime <- lapply(1:100,function(x){
        print(x)
        Fperm[,x]-apply(Fperm[,-x], 1, quantile, probs = 0.95, na.rm = TRUE)
      })

      x <- 29
      resid_q95_perm <- Fperm[,x]-apply(Fperm[,-x], 1, quantile, probs = 0.95, na.rm = TRUE)
      plot(resid_q95)
      abline(h=quantile(unlist(tmp),0.999,na.rm = TRUE))
      plot(resid_q95_perm)
      abline(h=quantile(unlist(tmp),0.999,na.rm = TRUE))
      th <- quantile(unlist(tmp),0.999,na.rm = TRUE)

      hist(sapply(tmp,function(x) length(which(x>th))))
      which.max(sapply(tmp,function(x) length(which(x>th))))

      length(which(resid_q95>th))

      F_obs <- emx_prime
      resid_mean <- F_obs - perm_mean
      resid_q95  <- F_obs - perm_q95
      resid_q99  <- F_obs - perm_q99

      resid_q95[resid_q95<0] <- 0
      resid_q99[resid_q99<0] <- 0
      resid_mean[resid_mean<0] <- 0

      perm_sd <- apply(Fperm, 1, sd, na.rm = TRUE)

      z_resid <- (F_obs - perm_mean) / perm_sd

      #plot(F_obs,resid_q95)

      par(mfcol=c(4,2))
      plot(resid_q95, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")
      plot(resid_q99, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")
      plot(z_resid, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")
      #
      plot(-log10(p.adjust(pf(resid_mean,1,123,lower.tail = FALSE),"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="obs")
      abline(h=1.3)

      F_obs <- Fperm[,84]
      resid_mean <- F_obs - perm_mean
      resid_q95  <- F_obs - perm_q95
      resid_q99  <- F_obs - perm_q99

      resid_q95[resid_q95<0] <- 0
      resid_q99[resid_q99<0] <- 0

      perm_sd <- apply(Fperm, 1, sd, na.rm = TRUE)

      z_resid <- (F_obs - perm_mean) / perm_sd


      plot(resid_q95, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="perm")
      plot(resid_q99, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="perm")
      plot(z_resid, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="perm")
      p_resid <- pf(resid_mean,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(pf(resid_mean,1,123,lower.tail = FALSE),"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="perm")

      F_obs <- Fperm[,1]
      perm_mu <- rowMeans(Fperm, na.rm=TRUE)
      perm_sd <- apply(Fperm, 1, sd, na.rm=TRUE)

      z <- (F_obs - perm_mu) / perm_sd
      p_z <- pnorm(z, lower.tail=FALSE)
      hist(p_z)

      chisq <- qchisq(1 - p_z, df=1)
      lambda <- median(chisq, na.rm=TRUE) / qchisq(0.5, df=1)
      plot(-log10(p.adjust(p_z,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),col=ifelse(map$type=="QTN","salmon","steelblue"),main="perm")
      abline(h=1.3)

      chisq(1-ppoints())

      lambda

      F_obs <- emx_prime
      z <- (F_obs - rowMeans(Fperm)) / apply(Fperm,1,sd)
      p <- pnorm(z, lower.tail = FALSE)

      plot(-log10(p.adjust(p,"fdr")))
      abline(h=1.3)

      p_raw <- pf(F_obs,1,123,lower.tail=FALSE)

      keep <- resid_q95 > 0
      plot(-log10(p_raw[keep]))

      pval_obs <- pf(emx_prime, df1=1, df2=123, lower.tail=FALSE)
      qval_obs <- p.adjust(pval_obs, method="fdr")

      resid <- emx_prime - Fperm

      outlier <- qval_obs < 0.05 & resid > 0



      q95_b <- apply(Fperm[, 51:100], 1, quantile, 0.95,na.rm=TRUE)



      res_a <- Fperm[,1] - q95_a
      res_b <- emx_prime - q95_b

      plot(res_a, pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_perm1")

      plot(tmp)

      plot(conf)

      gc()
      mclapply(1:ncol(Y),function(x){
        print(x)
        map_perm <- copy(map_org)

        for(ch in unique(map_perm$Chr_9sp)){
          idx <- which(map_perm$Chr_9sp==ch)
          GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm

          ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
          emx <- emmax(Y[,x],GTs[,idx],K = GRM)

          map_perm[idx,emx_F:=emx$F] ## add to map_perm
          emx_gif = map_perm[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
          map_perm[idx,emx_F:=emx_F/emx_gif]  ## genomic control

          ### === Latent factor mixed model analyses (LFMM) === ###

          # ## get K
          # xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
          # results <- xxx.pca1$x
          # km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)
          #
          # ## LFMM
          # write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
          # write.env(Y[,x], "./tmp/gradients.env")
          # project = NULL
          #
          # project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
          # pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))
          #
          # ## save F-value corrected for inflation
          # map_perm[idx,lfmm_F:=pv$fscores/pv$gif]
        }

        return(map_perm$emx_F)

      },mc.cores=8)

      map_perm <- copy(map_org)
      Y <- simulate_quant_pheno(K=GRM, h2 = 0, nrep = 100, seed = sample(1:100000,1))
      env_sim <- Y[, 1]
      #env_sim <- env
      for(ch in unique(map_perm$Chr_9sp)){
        idx <- which(map_perm$Chr_9sp==ch)
        GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm

        ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
        emx <- emmax(env_sim,GTs[,idx],K = GRM)

        map_perm[idx,emx_F:=emx$F] ## add to map_perm
        emx_gif = map_perm[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
        map_perm[idx,emx_F:=emx_F/emx_gif]  ## genomic control

        ### === Latent factor mixed model analyses (LFMM) === ###

        ## get K
        xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
        results <- xxx.pca1$x
        km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)

        ## LFMM
        write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
        write.env(env_sim, "./tmp/gradients.env")
        project = NULL

        project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
        pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))

        ## save F-value corrected for inflation
        map_perm[idx,lfmm_F:=pv$fscores/pv$gif]
      }
      map_perm1 <- copy(map_perm)

      map_perm <- copy(map_org)
      Y <- simulate_quant_pheno(K=GRM, h2 = 0, nrep = 1, seed = sample(1:100000,1))
      env_sim <- Y[, 1]
      #env_sim <- env
      for(ch in unique(map_perm$Chr_9sp)){
        idx <- which(map_perm$Chr_9sp==ch)
        GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE)$grm

        ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
        emx <- emmax(env_sim,GTs[,idx],K = GRM)

        map_perm[idx,emx_F:=emx$F] ## add to map_perm
        emx_gif = map_perm[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
        map_perm[idx,emx_F:=emx_F/emx_gif]  ## genomic control

        ### === Latent factor mixed model analyses (LFMM) === ###

        ## get K
        xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
        results <- xxx.pca1$x
        km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)

        ## LFMM
        write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
        write.env(env_sim, "./tmp/gradients.env")
        project = NULL

        project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
        pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))

        ## save F-value corrected for inflation
        map_perm[idx,lfmm_F:=pv$fscores/pv$gif]
      }
      map_perm2 <- copy(map_perm)
      #plot(map_perm$emx_F*ld_w)
      #emx_prime <- compute_Fprime(map$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      #emx_prime_perm <- compute_Fprime(map_perm2$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      #emx_prime_perm <- compute_Fprime(map_perm2$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      # emx_prime_perm2 <- compute_Fprime(map_perm2$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      #
      # plot(emx_prime_perm-emx_prime_perm2,pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),ylim=c(-100,100))
      # points(emx_prime-emx_prime_perm2,pch=ifelse(map$type=="QTN",3,1),cex=ifelse(map$type=="QTN",3,1), col="salmon")

      emx_prime_perm1 <- compute_Fprime(map_perm1$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime
      emx_prime_perm2 <- compute_Fprime(map_perm2$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)[[1]]$F_prime

      par(mfcol=c(5,1))
      p <- pf(emx_prime_perm1,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(p,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_perm1")
      abline(h=1.3)
      p <- pf(emx_prime_perm2,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(p,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_perm2")
      abline(h=1.3)
      p <- pf(emx_prime_perm2-emx_prime_perm1,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(p,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_perm1-F_prime_perm2")
      abline(h=1.3)
      p <- pf(emx_prime-emx_prime_perm1,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(p,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_obs-F_prime_perm1")
      abline(h=1.3)
      p <- pf(emx_prime-emx_prime_perm2,1,123,lower.tail = FALSE)
      plot(-log10(p.adjust(p,"fdr")),pch=ifelse(map$type=="QTN",3,20),cex=ifelse(map$type=="QTN",3,1),main="F_prime_obs-F_prime_perm2")
      abline(h=1.3)

      ld_w <-ld_ws[,1]
      emx_prime <- compute_Fprime(map$emx_F, ld_w, 100, nrow(GTs), enforce_null_floor = TRUE,full=FALSE)
      plot(emx_prime[[1]]$F_prime)
      #plot(ld_ws[,1])

      # draws_per_meth <- ld_rho_draws(gds,
      #                                ld_decay  = ld_decay,
      #                                F_vals     = map[,.(lfmm_F,emx_F)], ## the F values are pre-calculated and must be provided, these will be used for getting F_prime.
      #                                q_vals     = map[,.(lfmm_q,emx_q)], ## q-values from original analyses can also be used but not necessary
      #                                n_draws    = 1000,
      #                                stat_type  = "q",
      #                                rho        = NULL, ## grid of rho values used for ld_w
      #                                ld_ws      = ld_ws,
      #                                rho_d_lim  = list(min=0.5,max=0.99),
      #                                rho_ld_lim = list(min=0.5,max=0.99),
      #                                alpha_lim  = list(min=0.3,max=4), ## lowest alpha is 1/10^0.6=0.25; this range is defined in the -log10 scale!
      #                                lmin_lim   = list(min=1,max=10),
      #                                cores      = 8,
      #                                mode       = c("per_method")
      # )

      draws_joint_perm <- ld_rho_draws(gds,
                                       ld_decay  = ld_decay,
                                       F_vals     = map[,.(lfmm_F,emx_F)], ## the F values are pre-calculated and must be provided, these will be used for getting F_prime.
                                       q_vals     = NULL,#map[,.(lfmm_q,emx_q)], ## q-values from original analyses can also be used but not necessary
                                       n_draws    = 100,
                                       stat_type  = "q",
                                       rho        = NULL, ## grid of rho values used for ld_w
                                       ld_ws      = ld_ws,
                                       rho_d_lim  = list(min=0.5,max=0.99),
                                       rho_ld_lim = list(min=0.5,max=0.99),
                                       alpha_lim  = list(min=1.3,max=4), ## lowest alpha is 1/10^0.6=0.25; this range is defined in the -log10 scale!
                                       lmin_lim   = list(min=1,max=10),
                                       cores      = 8,
                                       mode       = c("joint")
      )
      map[,ld_w:=ld_ws[,"0.95"]]
      map[,lfmm_q_log := -log10(lfmm_q)]
      plot_manhattan(map=map,
                     gds,
                     ld_decay,
                     draws_joint_perm,
                     ## for defining ORs
                     sign_th=0.05,
                     mode="joint",
                     sign_if ="greater",
                     rho_d = 0.9,
                     rho_ld = 0.9,
                     ## outlier regiosn are defined based on the first in y_vars
                     y_vars = c("Joint_C","ld_w","lfmm_F","lfmm_q_log"),
                     y_labels = c("C (Joint analyses)","ld_w","lfmm_F","lfmm_q_log"),
                     titles = c("a) Joint analyses - C","b) ld_w","lfmm_F","lfmm_q_log"),
                     thresholds = c(0.05,NA,NA,1.3),
                     shape_var = "type",
                     col_var = "OR_id")

      plot(ld_ws[,"0.95"])

      C_sc <- consistency_score(draws_joint$draws[method=="Joint"])

      map <- add_consistency_to_map(map, consistency_obj = consistency_score(draws_joint$draws[method=="Joint"]))

      map_perm <- copy(map)
      draws_perm <- list(draws_joint)

      par(mfcol=c(2,1))
      map_obs[,plot(Joint_C,pch=ifelse(type=="QTN",3,20),cex=ifelse(type=="QTN",3,1),col=ifelse(type=="QTN","salmon","steelblue"))]
      map_perm[,plot(Joint_C,pch=ifelse(type=="QTN",3,20),cex=ifelse(type=="QTN",3,1),col=ifelse(type=="QTN","salmon","steelblue"))]


      plot_manhattan(map=map_obs,
                     gds,
                     ld_decay,
                     draws_joint,
                     ## for defining ORs
                     sign_th=0.05,
                     mode="joint",
                     sign_if ="greater",
                     rho_d = 0.9,
                     rho_ld = 0.9,
                     ## outlier regiosn are defined based on the first in y_vars
                     y_vars = c("Joint_C"),
                     y_labels = c("C (Joint analyses)"),
                     titles = c("a) Joint analyses - C"),
                     thresholds = c(0.05),
                     shape_var = type,
                     col_var = "OR_id")


      map
      map_obs[,plot(Joint_C,pch=as.numeric(as.factor(type)))]


      ## add log value for LFMM
      map[,log_lfmm_q := -log10(lfmm_q)]

      plot_manhattan(map,
                     gds,
                     ld_decay,
                     draws_pseudo,
                     ## for defining ORs
                     sign_th=0.05,
                     mode="joint",
                     sign_if ="greater",
                     rho_d = 0.9,
                     rho_ld = 0.9,
                     ## outlier regiosn are defined based on the first in y_vars
                     y_vars = c("Joint_C","log_lfmm_q"),
                     y_labels = c("C (Joint analyses)","-log10(q) | LFMM"),
                     titles = c("a) Joint analyses - C","b) Latent factor mixed model (LFMM) analyses"),
                     thresholds = c(0.05,-log10(0.05)),
                     col_var = "OR_id")

