library(data.table)
library(effectsize)
library(scales)
library(tidyr)
library(knitr)
library(pracma)
library(factoextra)
library(parallel)
library(wesanderson)
library(LEA)
library(egg)
library(igraph)
library(dplyr)
library(SNPRelate)
library(stats)
library(ggplot2)
library(data.table)
library(ggplot2)
library(ggsci)
library(LDscnR)
source("./R/emmax.R")

### --- Get focal QNT for a given SNP --- ###
#   gds - gds file generated by SNPrelate
#   map - The corresponding map file that contains at least columns "marker"
#     "and "type" where type=="QTN" are the potential focal QTN


focal_QTN <- function(map, qtn_col = "true_QTN") {


  #ch = "Chr1"
  rbindlist(lapply(unique(map$Chr), function(ch) {

    # map rows on this chromosome, restricted to SNPs present in GDS
    map_chr <- map[Chr == ch]

    markers_chr <- map_chr$marker

    qtn_chr <- map_chr[get(qtn_col) == TRUE, marker]

    if (length(qtn_chr) == 0L) {
      return(data.table(
        Chr = ch,
        marker = markers_chr,
        max_LD_with_QTN = 0,
        focal_QTN = NA_character_,
        bp_to_focal_QTN = NA_real_
      ))
    }


    r2 <- cor(GTs[, qtn_chr], GTs[,markers_chr],use = "pairwise.complete.obs")^2

    max_ld <- apply(r2, 2, max, na.rm = TRUE)
    focal_idx <- max.col(t(r2), ties.method = "first")
    focal_qtn <- qtn_chr[focal_idx]

    pos_vec <- map_chr$Pos
    names(pos_vec) <- map_chr$marker

    data.table(
      Chr = ch,
      marker = markers_chr,
      max_LD_with_QTN = max_ld,
      focal_QTN = focal_qtn,
      bp_to_focal_QTN = abs(pos_vec[markers_chr] - pos_vec[focal_qtn])
    )

  }), fill = TRUE)
}


# parsed files generated by ./R_simulations/Parse_raw_data_sim.R
files <- list.files("../LD-scaling-genome-scans/parsed_data/",full.names = TRUE)

#files <- files[grep("V0.5_c1_rep4",files)]

# split them into replicates (n=10) with the same landscape but different recombination maps, here only one replicate is provided (full data from Zenondo)
tmp <- do.call(rbind,strsplit(files,"/",fixed=TRUE))[,5]

files_split <- split(files, gsub(".rds","",apply(do.call(rbind,strsplit(tmp,"_",fixed=TRUE))[,2:4],1,paste,collapse="_")))

out_folder <- "./single_SNP_results/"
min_maf <- 0.1

# These are the pre-drawn individuals used for all
# Note that the parsed data contains data for 500 individuals, and these are a subsample of those
keep_125 <-readRDS("../LD-scaling-genome-scans/data/keep_inds_125.rds")
cores <- 8 # cores to use

message("\n\n#### ==== Starting outlier analyses ==== ####\n\n")

#fil <- files_split[[1]]
for(fil in files_split){
  # ------------------------ #
  # Read in and prepare data
  # ------------------------ #

  out_name <- paste(strsplit(basename(fil[1]),"_",fixed = TRUE)[[1]][c(2,3,4)],collapse="_")
  message("Processing ",out_name)
  ## read in data
  data <- lapply(fil, function(file) readRDS(file))
  map <- do.call(rbind,lapply(data,function(x)x$map))

  ## only if result file does not exist

  GTs <- do.call(cbind,lapply(data,function(x)x$GTs))


  #re-label chromosomes since we are concatenating data from 10 replicates
  new_order <- map[,order(Chr_9sp,-as.numeric(factor(Chr_type)))]
  GTs <- GTs[,new_order]
  setorder(map,Chr_9sp,Chr_type)

  levs <- map[!duplicated(paste(Chr_9sp,Chr_type))][,paste(Chr_9sp,Chr_type)]
  map[,LG:=as.numeric(factor(paste(Chr_9sp,Chr_type),levels=levs))]
  map[,Chr:=paste0("Chr",LG)]
  map[,marker:=paste(Chr,bp,sep=":")]
  setnames(map,"bp","Pos")
  colnames(GTs) <- map$marker
  env_ind <- data[[1]]$env[keep_125]
  env <- data[[1]]$env$env

  ## subsample -> reduce from 500 to 125 individuals
  env <- env[keep_125]
  GTs <- GTs[keep_125,]

  ## remove duplicate loci
  GTs <- GTs[,map[,which(!duplicated(marker))]]
  map <- map[!duplicated(marker)]

  ## recalculate maf for the subsample and filter anew

  maf_new <- colSums(GTs)/nrow(GTs)/2
  maf_new <- ifelse(maf_new<0.5,maf_new,1-maf_new)
  map[,maf:=maf_new]
  GTs <- GTs[,maf_new>min_maf]
  map <- map[maf>min_maf]


  setnames(map,c("V","c"),c("sel_int","disp_kernl"))

  qtn_rows <- map[,which(type=="QTN")]
  ## compute Va
  va <- sapply(qtn_rows, function(i){
    a  <- map$allelic_values[i]               # effect size α
    gt <- GTs[, i, drop=TRUE]                 # genotype 0/1/2
    p  <- mean(gt)/2                          # allele frequency
    2 * p * (1 - p) * a^2                     # Va formula
  })

  ## assign
  map[qtn_rows, Va := va]

  ## total Va per chromosome
  map[qtn_rows, sum_Va := sum(Va), by = Chr_9sp]

  ## proportion
  map[qtn_rows, p_Va := Va / sum_Va]

  ld_ws <- list()
  #ch <- 1
  ld_decay_chr_9sp <- lapply(unique(map$Chr_9sp),function(ch){
    ## generate gds file
    gds_path = tempfile(fileext = ".gds")
    gds <- create_gds_from_geno(geno = GTs[,map[,Chr_9sp==ch]],map=map[Chr_9sp==ch],gds_path)

    ## close at exit
    on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE)

    ld_decay <- compute_LD_decay(
      gds=gds,
      el_data_folder = NULL,
      n_win_decay = 20,
      max_SNPs_decay = Inf,
      keep_el = TRUE,
      slide=2000,
      cores = cores,
      ld_method = "corr"
    )
    as <- setNames(ld_decay$decay_sum$a_pred,ld_decay$decay_sum$Chr)
    bs <- setNames(ld_decay$decay_sum$b,ld_decay$decay_sum$Chr)
    cs <- setNames(ld_decay$decay_sum$c_pred,ld_decay$decay_sum$Chr)
    map[Chr_9sp==ch,a := as[Chr]]
    map[Chr_9sp==ch,b := bs[Chr]]
    map[Chr_9sp==ch,c := cs[Chr]]

    ld_ws[[ch]] <<- precalculate_ld_w(c(seq(0.1,0.95,by=0.05),0.99),ld_decay)

    ld_decay
  })


  ld_ws <- do.call(rbind,ld_ws)

  ## add decay info to map


  # ---------------------------------- #
  # Get focal QTN and associated data
  # ---------------------------------- #
  message("Get focal QTN \n")

  map[type == "QTN" & p_Va >= 0.05 & maf>0.1,true_QTN := TRUE]

  true_qtns <- map[true_QTN == TRUE, marker]

  fq <- focal_QTN(map, qtn_col = "true_QTN")

  map[fq, on = "marker",
      `:=`(
        focal_QTN = i.focal_QTN,
        bp_to_focal_QTN = i.bp_to_focal_QTN,
        max_LD_with_QTN = i.max_LD_with_QTN
      )]

  ## collect data
  map[type == "QTN", `:=`(
    focal_QTN = marker,
    max_LD_with_QTN = 1,
    bp_to_focal_QTN = 0
  )]

  map[Chr_type=="ntrl",bp_to_focal_QTN:=max(Pos)]
  map[Chr_type=="ntrl",max_LD_with_QTN:=0]

  map[, rho_d := a * bp_to_focal_QTN / (a * bp_to_focal_QTN + 1)]
  map[, ld_rel := (max_LD_with_QTN - b) / (c - b)]
  map[, ld_rel := pmin(pmax(ld_rel, 0), 1)]

  map[, true_pos := rho_d < 0.75 & ld_rel > 0.5]


  gds_path = tempfile(fileext = ".gds")
  gds <- create_gds_from_geno(geno = GTs,map=map,gds_path)
  on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE)

  message("Outlier analyses \n")
  for(ch in unique(map$Chr_9sp)){
    idx <- which(map$Chr_9sp==ch)
    GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,autosome.only = FALSE,snp.id = map[idx,marker])$grm

    ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
    emx <- emmax(env,GTs[,idx],K = GRM)

    map[idx,emx_F:=emx$F] ## add to map
    emx_gif = map[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
    map[idx,emx_F:=emx_F/emx_gif]  ## genomic control

    ### === Latent factor mixed model analyses (LFMM) === ###

    ## get K
    xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
    results <- xxx.pca1$x
    km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)

    ## LFMM
    write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
    write.env(env, "./tmp/gradients.env")
    project = NULL

    project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
    pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))

    ## save F-value corrected for inflation
    map[idx,lfmm_F:=pv$fscores/pv$gif]
  }

  map[,lfmm_p := pf(lfmm_F,1,nrow(GTs)-2,lower.tail = FALSE)]
  map[,emx_p := pf(emx_F,1,nrow(GTs)-2,lower.tail = FALSE)]
  map[,lfmm_q := p.adjust(lfmm_p,"fdr")]
  map[,emx_q := p.adjust(emx_p,"fdr")]


  out <- list(map=map,GTs=GTs,env=env,ld_ws=ld_ws,ld_decay_chr_9sp=ld_decay_chr_9sp)

  saveRDS(out,paste0(out_folder,out_name))

}



